package router

import (
	_ "beetle/docs" // Generated by `swag init`
	"beetle/internal/config"
	"beetle/internal/handler"

	"github.com/labstack/echo/v4"
)

type routeProvider interface {
	AddPublicRoutes(g *echo.Group, config config.Config)
	AddPrivateRoutes(g *echo.Group, config config.Config)
}

type Router struct {
	RouteProviders []routeProvider
	Config         config.Config
}

func New(config config.Config, userHandler *handler.UserHandler) *Router {
	return &Router{
		RouteProviders: []routeProvider{
			&tokenRouteProvider{},
			&healthcheckRouteProvider{},
			NewUserRouteProvider(userHandler),
			// TODO: Add more route providers here
		},
		Config: config,
	}
}

// AddRoutes adds all routes to the Echo instance
func (r *Router) AddRoutes(e *echo.Echo, authMiddlewares ...echo.MiddlewareFunc) {
	v1public := e.Group("/v1")
	v1private := e.Group("/v1", authMiddlewares...)

	for _, rp := range r.RouteProviders {
		rp.AddPrivateRoutes(v1private, r.Config)
	}

	for _, rp := range r.RouteProviders {
		rp.AddPublicRoutes(v1public, r.Config)
	}

	AddSwaggerRoutes(e, r.Config)

	// Add root routes
	e.GET("/", HomeHandler)
	e.GET("/health", HealthCheckHandler)
}

// HomeHandler handles the root endpoint
func HomeHandler(c echo.Context) error {
	return c.JSON(200, map[string]string{"message": "Welcome to the Beetle API"})
}

// HealthCheckHandler handles the health check endpoint
func HealthCheckHandler(c echo.Context) error {
	return c.JSON(200, map[string]string{"status": "healthy"})
}
